
[versions]
appcompat = "1.1.0"
firebaseCrashlyticsGradle = "3.0.6"
googleServices = "4.4.4"
gradle = "8.2.1"
material = "1.3.0"
constraintlayout = "2.1.4"
navigation = "2.3.5"
junit = "4.13.2"
ext_junit = "1.1.3"
espresso_core = "3.4.0"

prdownloader = "1.0.2"
volley = "1.2.1"
sdp = "1.1.0"

firebase_bom = "33.6.0"
firebase_analytics = "21.2.0"
firebase_crashlytics_ndk = "19.2.0"
firebase_messaging = "23.1.1"

ini4j = "0.5.4"
glide = "4.13.0"
lifecycle_process = "2.9.4"
paranoid = "0.3.14"
shadowhook = "1.0.10"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradle" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }

navigation_fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigation" }
navigation_ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigation" }

junit = { module = "junit:junit", version.ref = "junit" }
androidx_test_ext_junit = { module = "androidx.test.ext:junit", version.ref = "ext_junit" }
espresso_core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso_core" }

prdownloader = { module = "com.github.amitshekhariitbhu:PRDownloader", version.ref = "prdownloader" }
volley = { module = "com.android.volley:volley", version.ref = "volley" }
sdp = { module = "com.intuit.sdp:sdp-android", version.ref = "sdp" }

firebase_bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase_bom" }
firebase_analytics = { module = "com.google.firebase:firebase-analytics", version.ref = "firebase_analytics" }
firebase_crashlytics_ndk = { module = "com.google.firebase:firebase-crashlytics-ndk", version.ref = "firebase_crashlytics_ndk" }
firebase_messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebase_messaging" }

ini4j = { module = "org.ini4j:ini4j", version.ref = "ini4j" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
lifecycle_process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle_process" }
paranoid = { module = "com.joom.paranoid:paranoid-gradle-plugin", version.ref = "paranoid" }
shadowhook = { module = "com.bytedance.android:shadowhook", version.ref = "shadowhook" }

[plugins]
android_application = { id = "com.android.application", version = "8.2.1" }
google_services = { id = "com.google.gms.google-services", version = "4.4.4" }
firebase_crashlytics = { id = "com.google.firebase.crashlytics", version = "3.0.6" }
